### PR TITLE
RelayMockPayloadGenerator supports nested lists

### LINKED ISSUE #438: RelayPayloadMockGenerator doesn't support nested lists
RelayPayloadMockGenerator doesn't produce a correct output for nested lists. This is a regression for `graphql-js-operation-payload-generator` package compared to v0.8.5.

## How to reproduce

1. Add a nested list type to the schema `node_modules/relay-test-utils-internal/lib/testschema.graphql`
```graphql
type Query {
  ## Other root fields

  nestedList(id: ID!): [[Node!]!]!
}
```

2. Generate new schema types for tests: `yarn test:schema-types`

3. Add a test case:
```typescript
test("generate mock for nested list", () => {
  testGeneratedData(graphql`
    query RelayMockPayloadGeneratorNestedListTestQuery {
      nestedList(id: "my-nested-list-id") {
        __typename
        id
      }
    }
  `);
});
```

**Expected result:** test passes.

**Actual result:** test fails with `GraphQLError: Expected Iterable, but did not find one for field "Query.nestedList"`.

### PR DESCRIPTION
**Pull request by fidelman**
Closes #438

### CODE REVIEW

**Comment by fidelman** [comment]
> @fidelman please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Microsoft"

File: packages/graphql-js-operation-payload-generator/src/utils.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+  while (currentType instanceof GraphQLList) {
+    depth += 1;
+    currentType = getNullableType(currentType.ofType);
+  }
+
+  return depth;
+}
+
+export function wrapInArray(value: unknown, depth: number) {
```
Comment (user1736) [inline packages/graphql-js-operation-payload-generator/src/utils.ts:16]: can you give examples what's this used for? I read it as "burry element in nested arrays up to specified depth", but I can't really connect it to a real scenario. Does depth ever go above 2?

File: packages/graphql-js-operation-payload-generator/src/utils.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+  let result = value;
+
+  for (let i = 0; i < depth; i++) {
+    result = [result];
+  }
+
+  return result;
+}
+
+export function applyLogicToNestedArray<T, U>(
```
Comment (user1736) [inline packages/graphql-js-operation-payload-generator/src/utils.ts:26]: This looks like a piece of code that happened to be lumped together rather than a utility function. Probably it's not worth extracting at all.

File: packages/graphql-js-operation-payload-generator/src/utils.ts [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  value: T | T[],
+  someLogic: (item: T) => U,
```
Comment (user1736) [inline packages/graphql-js-operation-payload-generator/src/utils.ts:28]: nit: this usually named as `callback` or `iteratee`

**Review by user1736 — CHANGES_REQUESTED** [review]

File: packages/graphql-js-operation-payload-generator/src/utils.ts (hunk 1 above)
Comment (fidelman) [reply packages/graphql-js-operation-payload-generator/src/utils.ts:16]: My idea is to detect required depth for an array, without further limitation and hardcoding.
As it is open source, somebody maybe has a 3 dimensional array.

Comment (user1736) [reply packages/graphql-js-operation-payload-generator/src/utils.ts:16]: I'm still can't connect it to a use case. Can you provide a schema example with such type?

Comment (fidelman) [reply packages/graphql-js-operation-payload-generator/src/utils.ts:16]:
```
type Query {
        nestedList(id: ID!): [[CustomNode!]!]!
        deeplyNestedList(id: ID!): [[[CustomNode!]!]!]!
}
```

File: packages/graphql-js-operation-payload-generator/src/index.ts [hunk 4]
```diff
@@ -154,8 +159,11 @@ export function generate<TypeMap extends DefaultMockResolvers>(
         if (isList) {
           const value = source[selectionName];
           const result = Array.isArray(value)
-            ? value.map(generateValue)
-            : [generateValue(value as object)];
+            ? applyLogicToNestedArray(value, generateValue)
```
[the remark this answers is not in the document]
Comment (fidelman) [reply packages/graphql-js-operation-payload-generator/src/index.ts:162]: added tests

File: packages/graphql-js-operation-payload-generator/src/utils.ts (hunk 3 above)
Comment (fidelman) [reply packages/graphql-js-operation-payload-generator/src/utils.ts:28]: fixed

File: packages/graphql-js-operation-payload-generator/src/utils.ts (hunk 2 above)
Comment (fidelman) [reply packages/graphql-js-operation-payload-generator/src/utils.ts:26]: fixed

**Review by user1736 — APPROVED** [review]
